name: LaTeX Test

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  TAG: latex-container

jobs:
  LatexBuild:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2

      - name: use cache build
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.TAG }}
          load: true
          build-args: TS=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: docker build check
        if: ${{ failure() }}
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.TAG }}
          build-args: TS=${{ github.sha }}
          load: true
          pull: true
          no-cache: true
          cache-to: type=gha,mode=max

      - name: latex build sample
        run: |
          rm -f sample/*.pdf
          make run-sample
          make docker-stop
          if [ $(ls sample/ | grep -c .pdf) -eq 0 ]; then
            exit 1
          fi

      - name: latex build
        run: |
          rm -f sample/*.pdf
          make run
          make docker-stop
          if [ $(ls sample/ | grep -c .pdf) -eq 0 ]; then
            exit 1
          fi

      - name: lint
        run: |
          make github_actions_lint_
          ls
      - name: lint check
        run: |
          lint_cnt=$(cat lint.log | grep -c "error")
          if [ ${lint_cnt} -lt 1 ]; then
            exit 1
          fi
