name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  LatexBuild:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup docker
        uses: docker/setup-buildx-action
      - name: update
        run: |
          sudo apt update
          sudo apt upgrade -y
      - name: docker build
        run: |
          pwd
          make build
      - name: build
        run: |
          rm -f sample/*.pdf
          make sample
      - name: build check
        run: |
          if [ $(ls sample/ | grep -c .pdf) -eq 0 ]; then
            exit 1
          fi

  TextLint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup docker
        uses: docker/setup-buildx-action
      - name: update
        run: |
          sudo apt update
          sudo apt upgrade -y
      - name: docker build
        run: |
          pwd
          make build
      - name: lint
        run: |
          make github_actions_lint_
          ls
      - name: lint check
        run: |
          lint_cnt=$(cat lint.log | grep -c "error")
          if [ ${lint_cnt} -lt 1 ]; then
            exit 1
          fi
