name: LaTeX Build Test

# PushやPR時にテストを実行するAction

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

env:
  TAG: latex-container

jobs:
  LatexBuild:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]

    steps:
      - uses: actions/checkout@v4.1.7
      - name: Get current date and time
        env:
          TZ: "Asia/Tokyo"
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: docker build
        uses: ./.github/actions/dockerBuild
