name: Scheduled workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

permissions:
  contents: read

jobs:
  image-test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: ./.github/actions/pull

  image-test-arm64:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: ./.github/actions/pullArm

  latest-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.2
      - name: docker build
        uses: ./.github/actions/dockerBuild

  latest-ubuntu-arm64:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.2
      - name: docker build
        uses: ./.github/actions/dockerBuildArm
