name: docker hub

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  get-image:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup docker
        uses: docker/setup-buildx-action@v2
      - name: docker pull
        run: |
          make get-image
      - name: tex build
        run: |
          rm -f sample/*.pdf
          make sample
      - name: build check
        run: |
          if [ $(ls sample/ | grep -c .pdf) -eq 0 ]; then
            ls -l
            exit 1
          elif [ $(ll sample | grep semi.pdf | cut -d " " -f 6) -eq 0 ]
            ls -l
            exit 1
          fi
