name: Scheduled workflow

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  get-image:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup docker
        uses: docker/setup-buildx-action@v2
      - name: docker pull
        run: |
          make get-image
      - name: tex build
        run: |
          rm -f sample/*.pdf
          make run-sample
      - name: build check
        run: |
          if [ $(ls sample/ | grep -c .pdf) -eq 0 ]; then
            ls -l
            exit 1
          elif [ $(ls -l sample | grep semi.pdf | cut -d " " -f 5) -eq 0 ]; then
            ls -l
            exit 1
          fi

  DockerCacheSave:
    runs-on: ubuntu-22.04
    steps:
      # リポジトリの読み込み（fetch-depth=1）
      - name: Check out repo under workspace
        uses: actions/checkout@v2
      - name: setup docker
        uses: docker/setup-buildx-action@v2

      - name: use cache build
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.TAG }}
          load: true
          build-args: TS=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: docker build check
        if: ${{ failure() }}
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.TAG }}
          build-args: TS=${{ github.sha }}
          load: true
          pull: true
          no-cache: true
          cache-to: type=gha,mode=max
