name: Scheduled workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

permissions:
  contents: read

jobs:
  image-test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1
      - name: setup docker
        uses: docker/setup-buildx-action@v3.0.0
      - name: docker pull
        run: make get-image
      - name: build test
        run: make test --trace

  image-testOnArm:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1
      - name: setup docker
        uses: docker/setup-buildx-action@v3.0.0
      - name: install qemu
        run: |
          apt-get update
          apt-get install -y qemu-user-static

      - name: docker pull
        run: make get-image ARCH=arm64
      - name: build test
        run: make test ARCH=arm64 --trace

  latest-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1
      - name: setup docker
        uses: docker/setup-buildx-action@v3.0.0
      - name: docker rebuild
        run: |
          make docker-rebuild
      - name: build test
        run: make test --trace
