name: Scheduled workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

permissions:
  contents: read

jobs:
  image-test:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1
      - name: setup docker
        uses: docker/setup-buildx-action@v3.0.0

      - name: docker pull
        run: make get-image

      - name: build test
        run: |
          make test | tee result.log || true
          if [[ $(cat result.log | grep -c FAILED) -ne 0 ]]; then
            make test --trace
          fi

  image-test-arm64:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1
      - name: setup docker
        uses: docker/setup-buildx-action@v3.0.0

      - name: install qemu
        run: sudo apt-get install qemu-user-static

      - name: docker pull
        run: make get-image ARCH=arm64

      - name: build test
        run: |
          make test ARCH=arm64 | tee result.log || true
          if [[ $(cat result.log | grep -c FAILED) -ne 0 ]]; then
            make test ARCH=arm64 --trace
          fi

  latest-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1
      - name: setup docker
        uses: docker/setup-buildx-action@v3.0.0
      - name: docker build
        run: |
          make docker-build
      - name: build test
        run: |
          make test | tee result.log || true
          if [[ $(cat result.log | grep -c FAILED) -ne 0 ]]; then
            make test --trace
          fi
