name: docker image upload

on:
  push:
    branches: master
  workflow_dispatch:

permissions:
  contents: read

env:
  TAG: latex-container

jobs:
  LatexImagePush:
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v4.1.0
      - uses: docker/setup-buildx-action@v3.0.0

      - name: docker build
        needs: [LatexBuild]
        uses: ./.github/workflows/build.yml

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push image
        run: make push image
        timeout-minutes: 60

  LatexImagePushArm64:
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v4.1.0
      - uses: docker/setup-buildx-action@v3.0.0
      - name: install qemu
        run: sudo apt-get install qemu-user-static

      - name: docker build
        needs: [LatexBuildForArm]
        uses: ./.github/workflows/build.yml

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push arm64 image
        run: make push imageforArm
        timeout-minutes: 60
