name: docker image upload

on:
  push:
    branches: master
  workflow_dispatch:

permissions:
  contents: read

env:
  TAG: latex-container

jobs:
  LatexImagePush:
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v4.1.0
      - uses: docker/setup-buildx-action@v3.0.0

      - name: docker build
        run: |
          make docker-rebuild --trace
          docker images
        timeout-minutes: 30

      - name: build test
        run: make test --trace

      - name: build test
        run: |
          make test --trace | tee buildTest.log
          if [[ -z $(cat buildTest.log | grep "SUCCESS!") ]]; then
            exit 1
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/semi-latex:latest
        timeout-minutes: 60

  LatexImagePushArm64:
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v4.1.0
      - uses: docker/setup-buildx-action@v2.9.1
      - name: install qemu
        run: sudo apt-get install qemu-user-static

      - name: docker build
        run: |
          make docker-rebuildforArm --trace
          docker images
        timeout-minutes: 60

      - name: build test
        run: make test ARCH=arm64 --trace

      - name: build test
        run: |
          make test ARCH=arm64 --trace | tee buildTest.log
          if [[ -z $(cat buildTest.log | grep "SUCCESS!") ]]; then
            exit 1
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: DockerfileArm
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/semi-latex:arm64
        timeout-minutes: 60
